(tc -)
(load "shen/interp.shen")
(tc -)
(load "shen/compile.shen")
(load "shen/load.shen")

(interp-load "/home/arch/github/shen-scheme/kl/core.kl")
(interp-load "/home/arch/github/shen-scheme/kl/declarations.kl")
(interp-load "/home/arch/github/shen-scheme/kl/types.kl")
(interp-load "/home/arch/github/shen-scheme/kl/macros.kl")
(interp-load "/home/arch/github/shen-scheme/kl/load.kl")
(interp-load "/home/arch/github/shen-scheme/kl/toplevel.kl")
(interp-load "/home/arch/github/shen-scheme/kl/sys.kl")
(interp-load "/home/arch/github/shen-scheme/kl/dict.kl")
(interp-load "/home/arch/github/shen-scheme/kl/track.kl")
(interp-load "/home/arch/github/shen-scheme/kl/reader.kl")
(interp-load "/home/arch/github/shen-scheme/kl/compiler.kl")
(interp-load "/home/arch/github/shen-scheme/kl/writer.kl")
(interp-load "/home/arch/github/shen-scheme/kl/yacc.kl")
(interp-load "/home/arch/github/shen-scheme/kl/prolog.kl")
(interp-load "/home/arch/github/shen-scheme/kl/sequent.kl")
(interp-load "/home/arch/github/shen-scheme/kl/t-star.kl")
(interp-load "/home/arch/github/shen-scheme/kl/overrides.kl")
(interp-load "/home/arch/github/shen-scheme/kl/extension-expand-dynamic.kl")
(interp-load "/home/arch/github/shen-scheme/kl/extension-features.kl")
(interp-load "/home/arch/github/shen-scheme/kl/extension-launcher.kl")
(interp-load "/home/arch/github/shen-scheme/kl/extension-programmable-pattern-matching.kl")
(interp-load "/home/arch/github/shen-scheme/kl/shen-scheme-extensions.kl")
(interp-load-raw "/home/arch/github/shen-scheme/kl/stlib.kl")
(interp-load-raw "/home/arch/github/shen-scheme/kl/init.kl")

(define entry-str
  [N [lambda Code []]] -> (cn (cn (cn (cn "(" (csexp-atom N)) " ")
                                  (zinc->native [cur Code]))
                             ")")
  _ -> "")

(define entries-str
  [] -> ""
  [E | Rest] -> (cn (entry-str E) (entries-str Rest))
  _ -> "")

(set *bundle* (cn (cn "(" (entries-str (dedupe-globals (value global-table)))) ")"))
(set *out* (open "globals.csexp" out))
(pr (value *bundle*) (value *out*))
(close (value *out*))
